name: Pytest

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            libegl1 \
            libxkbcommon0 \
            libxkbcommon-x11-0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest
